### ISSUE TITLE
README link broken

### ISSUE THREAD

**Issue by ofaurax** [STMicroelectronics/stm32ai#2]
In your README.md, https://www.st.com/stm32cubeai is broken.

**Comment by vinceab** [comment]
Hi @ofaurax,

I just test the link https://www.st.com/stm32cubeai and it is working => redirection to https://www.st.com/content/st_com/en/ecosystems/artificial-intelligence-ecosystem-stm32.html.

Can you please check it again?

Thanks
Vincent

**Comment by ofaurax** [comment]
Very weird, it's OK now... I got 404 last time. Anyway, closed, thank you!
